name: Upload File

on:
  push:
    paths:
      - "uploads/**"

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send files to Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          for file in uploads/*; do
            curl -F chat_id="$CHAT_ID" \
                 -F audio=@"$file" \
                 "https://api.telegram.org/bot${BOT_TOKEN}/sendAudio"
          done
